//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACD2ICR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string DBServer {
            get {
                return ((string)(this["DBServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("icresponse")]
        public string DBName {
            get {
                return ((string)(this["DBName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rootalso")]
        public string DBUser {
            get {
                return ((string)(this["DBUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A9m1n")]
        public string DBPass {
            get {
                return ((string)(this["DBPass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://acd2.ststelecom.com/QueueManager/Login.php?ret_link=%2FQueueManager%2Fage" +
            "nt_ctl.php&type=notLogged&ccsForm=Login")]
        public string ACDLoginUrl {
            get {
                return ((string)(this["ACDLoginUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://acd2.ststelecom.com/QueueManager/activity_monitor.php")]
        public string ACDOverViewUrl {
            get {
                return ((string)(this["ACDOverViewUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://acd2.ststelecom.com/QueueManager/ReadyBusy.php?paused=0")]
        public string ACDGoBusy {
            get {
                return ((string)(this["ACDGoBusy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://acd2.ststelecom.com/QueueManager/ReadyBusy.php?paused=1")]
        public string ACDGoReady {
            get {
                return ((string)(this["ACDGoReady"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO acdoverview (name, date, phone, status,passed) VALUES (?name, ?date, " +
            "?phone, ?status, ?passed)")]
        public string DBInsertOverview {
            get {
                return ((string)(this["DBInsertOverview"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO calls(uid, status, date, startTime, holdtime, duration, tech, queuena" +
            "me) VALUES (?uid, ?status, ?date, ?startTime, ?holdtime, ?duration, ?tech, ?queu" +
            "ename)")]
        public string DBInsertActiveCalls {
            get {
                return ((string)(this["DBInsertActiveCalls"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vm.ststelecom.com/portal/")]
        public string VMLoginUrl {
            get {
                return ((string)(this["VMLoginUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vx2.voip.mia1.net.ststelecom.com:8082/VXView")]
        public string VMVXView {
            get {
                return ((string)(this["VMVXView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vx2.voip.mia1.net.ststelecom.com:8082/VXView/")]
        public string VMVXViewRoot {
            get {
                return ((string)(this["VMVXViewRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vx2.voip.mia1.net.ststelecom.com:8082/VXView/VXView.do")]
        public string VMVXViewDo {
            get {
                return ((string)(this["VMVXViewDo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vx2.voip.mia1.net.ststelecom.com:8082/VXView/login.do")]
        public string VMVXViewLogin {
            get {
                return ((string)(this["VMVXViewLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vx2.voip.mia1.net.ststelecom.com:8082/VXView/jsp/top.jsp")]
        public string VMVXViewJSPTop {
            get {
                return ((string)(this["VMVXViewJSPTop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vx2.voip.mia1.net.ststelecom.com:8082/VXView/jsp/navigation.jsp")]
        public string VMVXViewJSPNav {
            get {
                return ((string)(this["VMVXViewJSPNav"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SMTPport {
            get {
                return ((int)(this["SMTPport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string SMTPhost {
            get {
                return ((string)(this["SMTPhost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("icr.reports@gmail.com")]
        public string SMTPusername {
            get {
                return ((string)(this["SMTPusername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Samurai8")]
        public string SMTPpassword {
            get {
                return ((string)(this["SMTPpassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICRealtime Reports")]
        public string SMTPsubjectline {
            get {
                return ((string)(this["SMTPsubjectline"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\ICRmonthlyReportsRecipients.txt")]
        public string EMAILlistfilepath {
            get {
                return ((string)(this["EMAILlistfilepath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Call Center Report")]
        public string EMAILmessageheader {
            get {
                return ((string)(this["EMAILmessageheader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int EMAILsendtime {
            get {
                return ((int)(this["EMAILsendtime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT tech,AVG(TIME_TO_SEC(TIMEDIFF(stopTime,startTime))) AS TechAverageDuration" +
            ",COUNT(*) AS NumOfRows FROM calls WHERE date=CURDATE() GROUP BY tech")]
        public string DBGetAgentDailyStats {
            get {
                return ((string)(this["DBGetAgentDailyStats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT tech,AVG(TIME_TO_SEC(TIMEDIFF(stopTime,startTime))) AS TechAverageDuration" +
            ",COUNT(*) AS NumOfRows FROM calls WHERE date BETWEEN DATE_SUB(CURDATE(),INTERVAL" +
            " 30 DAY) AND CURDATE() GROUP BY tech")]
        public string DBGetMonthlyReport {
            get {
                return ((string)(this["DBGetMonthlyReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://acd2.ststelecom.com/QueueManager/queuecalls.php?s_call_date=&s_end_date=&" +
            "s_unique_id=&s_ani=&s_abandoned=&s_call_type=&s_agent_name=&s_queue_name=&queue_" +
            "callsOrder=&queue_callsDir=&queue_callsPageSize=100&queue_callsPage=")]
        public string ACDQueueLanding {
            get {
                return ((string)(this["ACDQueueLanding"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE calls SET status=?status,startTime = ?startTime, stopTime =?stopTime, hold" +
            "time=?holdtime, duration=?duration WHERE uid=?uid")]
        public string DBInsertCompletedCall {
            get {
                return ((string)(this["DBInsertCompletedCall"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) AS NumOfRows FROM calls WHERE uid=")]
        public string DBCheckUID {
            get {
                return ((string)(this["DBCheckUID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT status, holdtime, duration FROM calls WHERE uid=")]
        public string DBGetCallRecordByUID {
            get {
                return ((string)(this["DBGetCallRecordByUID"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) AS NumOfRows FROM calls WHERE name=")]
        public string DVCheck_OviewViewURL {
            get {
                return ((string)(this["DVCheck_OviewViewURL"]));
            }
            set {
                this["DVCheck_OviewViewURL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRUNCATE TABLE acdoverview")]
        public string ACDTrunc {
            get {
                return ((string)(this["ACDTrunc"]));
            }
        }
    }
}
